name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout                   repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # 3️⃣     Instal   l f    rontend dependencies
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --include=dev

      - name: Build frontend
        working-directory: frontend
        run: node node_modules/vite/bin/vite.js build

      # 4️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ap-south-1

      # 5️⃣ Validate & Build SAM backend
      - name: Validate and Build SAM backend
        working-directory: sam
        run: |
          sam validate
          sam build

      # 6️⃣ Deploy SAM backend
      - name: Deploy SAM backend
        working-directory: sam
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      # 7️⃣ Fetch frontend S3 bucket name from CloudFormation
      - name: Get S3 bucket name
        id: get-bucket
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks \
            --stack-name cab-mobility-app-1 \
            --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" \
            --output text)
          echo "bucket=$BUCKET_NAME" >> $GITHUB_OUTPUT

      # 8️⃣         Upload frontend build to S3

      - name: Upload frontend to S3
        run: |
          aws s3 sync frontend/dist s3://${{ steps.get-bucket.outputs.bucket }} --delete
